import Head from 'next/head';
import { useState } from 'react';
import Hello from '/src/pages/Hello.js';



export default function Home() {


  return (
    <>
      <Head>
        <title>Lefty Design</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
    <Hello />
    
     
    </>
  )
}
