import Head from 'next/head';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import { useState } from 'react';
import Hello from '/src/pages/Hello.js';
import Directory from '/src/pages/Directory.js';


const inter = Inter({ subsets: ['latin'] })


export default function Home() {

  const [splash, setSplash] = useState(true);

  return (
    <>
      <Head>
        <title>Lefty Design</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div onClick={()=> { setSplash(false)}}>
    { splash === true ? <Hello /> : <Directory /> }

    </div>
     
    </>
  )
}
